using DevExpress.XtraPivotGrid;
using System.Drawing;
using System.Windows.Forms;

namespace PivotCustomDraw {
    public partial class Form1 : Form {
        public Form1() {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the ExcelDataSource
            excelDataSource1.Fill();
        }
        private void pivotGridControl1_CustomDrawCell(object sender, PivotCustomDrawCellEventArgs e) {
            Rectangle r;
            // Paints Row Grand Totals.
            if (e.RowValueType == PivotGridValueType.GrandTotal) {
                Brush brushFillTotals;
                brushFillTotals = e.GraphicsCache.GetSolidBrush(ColorTranslator.FromHtml("#0099cc"));
                r = e.Bounds;
                e.GraphicsCache.FillRectangle(brushFillTotals, e.Bounds);
                r.Inflate(-4, -4);
                e.GraphicsCache.DrawString(e.DisplayText, e.Appearance.Font,
                Brushes.White, r, e.Appearance.GetStringFormat());
                e.Handled = true;
                return;
            }
            // Paints the data cells.
            Brush brushFill;
            r = e.Bounds;
            if (e.Focused)
                // Initializes the brush used to paint the focused cell.
                brushFill = e.GraphicsCache.GetSolidBrush(Color.White);
            else
                if (e.Selected)
                // Initializes the brush used to paint selected cells.
                brushFill = e.GraphicsCache.GetSolidBrush(ColorTranslator.FromHtml("#b6e7eb"));
            else
                // Initializes the brush used to paint data cells.
                brushFill = e.GraphicsCache.GetSolidBrush(ColorTranslator.FromHtml("#ecfbf8"));

            e.GraphicsCache.DrawRectangle(Pens.DimGray, r);
            r.Inflate(-1, -1);
            e.GraphicsCache.FillRectangle(brushFill, r);
            if (e.Focused) {
                r.Inflate(-1, -1);
                e.GraphicsCache.DrawRectangle(e.GraphicsCache.GetPen(ColorTranslator.FromHtml("#f05b41"),
                    3), r);
            }
            r.Inflate(-4, -4);
            e.Appearance.DrawString(e.GraphicsCache, e.DisplayText, r);
            e.Handled = true;
        }
    }
}
